config/routes.rb
Sechandgood::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :goods
  resources :categories, only: [:index, :new, :create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/goods/:id/signforit', to: 'goods#signforit', via: 'post'
  match '/validate/:validate', to: 'users#validate', via: 'get'
  match '/search', to: 'goods#search', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @categories = Category.limit(3)
    @category = params[:category]
    if !@category
      @goods = Good.paginate(page: params[:page])
    else
      @category = Category.where("id = ?", @category).first
      if @category
        @more = false
        @categories.each do |tmp|
          @more ||= @category == tmp
        end
        @goods = @category.goods.paginate(page: params[:page])
      else
        @goods = Good.paginate(page: params[:page])
      end
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  A project for our class!
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
 Contact us!
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
 Welcome to us! 
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<ul class="nav nav-tabs nav-justified home-tabs">
  <li <% if !@category %> class="active" <% end %> ><%= link_to "All", root_path %></li>
<% @categories.each do |tmp| %>
  <li <% if @more && @category && @category == tmp %> class="active" <% end %> ><%= link_to tmp.title.capitalize, root_path(category: tmp.id) %></li>
<% end %>

  <% if !@more && @category %><li class="active"><%= link_to @category.title.capitalize, root_path(category: @category.id) %></li><% end %>

  <li> <%= link_to "More", categories_path %></li>
</ul>

<ol class="goods">
  <%= render partial: "shared/show_goods", collection: @goods, as: "good" %>
</ol>
<%= will_paginate @goods %>