config/routes.rb
Sechandgood::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :goods
  resources :categories, only: [:index, :new, :create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/goods/:id/signforit', to: 'goods#signforit', via: 'post'
  match '/validate/:validate', to: 'users#validate', via: 'get'
  match '/search', to: 'goods#search', via: 'get'

end

app/models/good.rb
class Good < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :signs, dependent: :destroy
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 1000 }
  searchable do
    text :title, boost: 5.0
    text :content, boost: 4.0
    text :user, boost: 1.0 do
      user.name
    end
    text :category do
      category.title
    end
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy, :new, :edit, :update]
  before_action :correct_user, only: [:destroy, :update, :edit]
  before_action :auth_for_sign, only: :signforit
  def index

  end

  def new
    @good = current_user.goods.build
    @categories = Category.all.map { |tmp| [tmp.title, tmp.id] }
  end
  
  def show
    @good = Good.find(params[:id])
  end

  def create
    @good = current_user.goods.build(good_params)
    if @good.save
      flash[:success] = "Good created!"
      redirect_to root_url
    else
      @categories = Category.all.map { |tmp| [tmp.title, tmp.id] }
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map { |tmp| [tmp.title, tmp.id] }
  end

  def update
    if @good.update_attributes(good_params)
      flash[:success] = "Good updated"
      redirect_to @good
    else
      @categories = Category.all.map { |tmp| [tmp.title, tmp.id] }
      render 'edit'
    end
  end

  def destroy
    @good.destroy
   redirect_to root_url 
  end

  def signforit
    tmp = Good.find(params[:id])
    sign = tmp.signs.build
    current_user.signs << sign
    sign.save!
    respond_to do |format|
      format.html { render text: tmp.user.contact }
    end
  end
  
  def search
    @goods = Good.search do
      fulltext params[:query]
      paginate page: params[:page]
    end
    @goods = @goods.results
  end

  private

    def good_params
      params.require(:good).permit(:title, :content, :category_id)
    end

    def auth_for_sign
      unless signed_in?
        session[:return_to]="/goods/#{params[:id]}"
        flash[:notice] = "Please sign in."
        respond_to do |format|
          format.html { render text: signin_url, status: 401 }
        end
      end
    end

    def correct_user
      @good = current_user.goods.find_by(id: params[:id])
      redirect_to root_url if @good.nil?
    end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_good.html.erb
<li>
  <span class="title"><%= good.title %>
  <% if current_user?(good.user) %>
    | <%= link_to "edit", edit_good_path(good) %>
    | <%= link_to "delete", good, method: :delete, 
                                data:{ confirm: "You sure?" },
                                title: good.title %>
  <% elsif current_user && current_user.signs.where("good_id=?", good.id).first %>
    | <a><%= good.user.contact %></a>
  <% else %>
    <input type="hidden" name="id" value="<%=good.id %>"/>
    | <a class="signforit">Sign for it</a>
  <% end %></span>
  <span class="content"><%= good.content.html_safe %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(good.created_at) %> ago.
  </span>  
</li>

app/views/goods/edit.html.erb
<script>
  $(function(){
    $("textarea").wysihtml5();
  });
</script>
<div class="row">
  <div class="span8 offset1">
    <%= form_for(@good) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title %>
      
      <%= f.label :content %>
      <%= f.text_area :content %>

      <%= f.label :category_id %>
      <%= f.select :category_id, @categories %>

      <%= f.submit "Save changes", class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/goods/new.html.erb
<script>
  $(function(){
    $("textarea").wysihtml5();
  });
</script>
<div class="row">
  <div class="span8 offset1">
    <%= form_for(@good) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title %>
      
      <%= f.label :content %>
      <%= f.text_area :content %>

      <%= f.label :category_id %>
      <%= f.select :category_id, @categories %>
      <button class="btn btn-primary" type="submint">Post</button>
      <button class="btn btn-danger" type="reset">Clear</button>
    <% end %>
  </div>
</div>

app/views/goods/search.html.erb
<ol class="goods">
  <%= render partial: "shared/show_goods", collection: @goods, as: "good" %>
</ol>

<%= will_paginate @goods %>

app/views/goods/show.html.erb
<% content_for :head do %>
  <script>
    $(function(){
      $("a.signforit").click(function(){
        var id = $(this).prev(":input[name='id']").val();
        var nowat = $(this)
        $.ajax("/goods/"+id+"/signforit", {
          type: "POST",
          statusCode: {
            401: function(result){
              window.location.href = result.responseText;
            }
          },
          success: function(result){
            nowat.removeClass("signforit").html(result).prev(":input[name='id']").remove();
          }
        });
      });
    });
  </script>
<% end %>
<div class="goods">
  <%= render @good %>
</div>