config/routes.rb
Sechandgood::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :goods
  resources :categories, only: [:index, :new, :create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/goods/:id/signforit', to: 'goods#signforit', via: 'post'
  match '/validate/:validate', to: 'users#validate', via: 'get'
  match '/search', to: 'goods#search', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Sechand</a>
    by Group
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Sechand", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <li><%= link_to "Sign up", new_user_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_subheader.html.erb
<div class="row">
<div class="subheader">
  <div class="span7 offset3">
    <%= form_tag search_path, method: :get, class: "form-inline" do %>
      <div class="form-group">
        <%= text_field_tag :query, params[:query], class: "form-control span6 search-query", placeholder: "Search for goods" %>
      </div>
      <%= submit_tag "Search", class: "btn" %>
    <% end %>
  </div>
  <div class="span4 offset1">
    <a href="<%= new_good_path %>" class="btn btn-primary" type="button">Post Good</a>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= yield(:head) %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/subheader' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <div class="container">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>